# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: huhobert <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/07/18 15:18:54 by huhobert          #+#    #+#              #
#    Updated: 2019/07/18 15:26:59 by huhobert         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

RM = rm -f

all: $(NAME)

$(NAME):
	gcc -Wall -Wextra -Werror -o $(NAME) read.c


clean:
	/bin/$(RM) $(NAME)
fclean: clean
	/bin/$(RM) $(NAME)
