# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: huhobert <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/07/16 11:08:00 by huhobert          #+#    #+#              #
#    Updated: 2019/07/16 15:24:28 by huhobert         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do-op

RM = rm -f

all: $(NAME)

$(NAME):
	gcc -Wall -Wextra -Werror -o $(NAME) fun.c main.c write.c ft_atoi.c


clean:
	$(RM) $(NAME)
